### ISSUE TITLE
Replace local cache with redis

### ISSUE THREAD

**Issue by teodorescuserban** [HXLStandard/hxl-proxy#193] opened 2018-04-13 11:19 UTC
Local cache does not scale.

Lets enable multiple instances to share the same cache by using redis (having the option to use redis instead of the default cache would be even better)

**Comment by teodorescuserban** [comment] 2019-03-06 08:28
but. but...why? :)

**Comment by davidmegginson** [comment] 2019-03-07 20:30
Hi, @teodorescuserban . I noticed that the issue was stale (had been sitting around a while with no action), so I closed it. Reopening.

**Comment by teodorescuserban** [comment] 2019-03-15 14:00
Thank you. I think soon it would be worth it, as I see more and more talks on the cache.

**Comment by davidmegginson** [comment] 2019-06-06 20:58
Replaced with https://humanitarian.atlassian.net/browse/HXL-5

**Comment by davidmegginson** [comment] 2019-12-16 14:17
Reopening, since (for now) managing issue back on GitHub. Planning for the next release.

**Comment by davidmegginson** [comment] 2019-12-16 14:21
There are two places we need to replace the caching:

1. [flask-caching](https://flask-caching.readthedocs.io/en/latest/) package (for data output) — has a [redis backend](https://flask-caching.readthedocs.io/en/latest/#rediscache)
2. [requests_cache](https://requests-cache.readthedocs.io/en/latest/) package (for data input)  — has a [redis backend](https://requests-cache.readthedocs.io/en/latest/api.html#requests-cache-backends-redis)

**Comment by davidmegginson** [comment] 2019-12-17 18:59
Installing redis in my local system:

    $ sudo apt install redis-server
    $ sudo systemctl status redis # confirm it's running

**Comment by davidmegginson** [comment] 2019-12-17 20:55
redis caching for output is working on my local laptop. Confirmed that the new keys were created in redis. Looking at input caching (requests-cache) now.

**Comment by davidmegginson** [comment] 2019-12-17 21:23
Basic input caching working now. Need to add support for host/port/db parameters for a remote redis cache.

**Comment by davidmegginson** [comment] 2020-02-18 15:21
Closing this issue. Will make a new one for further refinement/testing.

**Closed by davidmegginson** 2020-02-18 15:21 UTC
Labels: type:refactoring
