### ISSUE TITLE
Bug in error value reporting

### ISSUE THREAD

**Issue by cjhendrix** [HXLStandard/hxl-proxy#210] opened 2018-04-25 08:55 UTC
https://beta.proxy.hxlstandard.org/data/validate?url=https%3A//docs.google.com/spreadsheets/d/1NXG_M2yTrdk5LS7FgUBVHbo6ZdMt3Wmo6jE0oVws2vA/export%3Fformat%3Dcsv&schema_url=https%3A//raw.githubusercontent.com/OCHA-DAP/tools-datacheck-validation/master/validation-schema-sle.json&details=V97Ua478

The source file and the ITOS output all use capitalized "SL01".   But for this validation, the error is returned in lower case.   

![image](https://user-images.githubusercontent.com/1654485/39235794-32355d8c-4877-11e8-8907-c93fcc7cbddf.png)

The recipe for this validation is 

```
{
#valid_tag: "#adm1+code",
#valid_severity: "error",
#valid_correlation: "adm1+name",
#valid_value+url: "http://beta.proxy.hxlstandard.org/pcodes/sle-adm1.csv",
#description: "Invalid combination of p-code and administrative unit name found"
},
```

The same problem occurs when validating one-to-one combinations within the source file only using this recipe:

```{
#valid_tag: "#adm1+code",
#valid_severity: "error",
#valid_correlation: "adm1+name",
#description: "P-code and admin unit name combinations not consistent"
},
```

**Comment by davidmegginson** [comment] 2018-04-27 00:40
This will be fixed in HXLStandard/libhxl-python#140

**Comment by davidmegginson** [comment] 2018-05-02 19:55
The referenced schema is no longer in the master HEAD in git, so CJ's validation link fails. Here's a revised link that uses an older version of the branch:

https://beta.proxy.hxlstandard.org/data/validate?url=https%3A//docs.google.com/spreadsheets/d/1NXG_M2yTrdk5LS7FgUBVHbo6ZdMt3Wmo6jE0oVws2vA/export%3Fformat%3Dcsv&schema_url=https%3A//raw.githubusercontent.com/OCHA-DAP/tools-datacheck-validation/493c8da038b5ded0ac930536e3857511c9bc0e3f/validation-schema-sle.json&details=V97Ua478

**Comment by davidmegginson** [comment] 2018-05-28 22:39
Confirmed fixed in above link (due to other code changes). Suggested correction now preserves case.

**Closed by davidmegginson** 2018-05-28 22:39 UTC
Labels: type:bug
