### ISSUE TITLE
validation log: col is not reflecting the column index

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#207] opened 2018-04-24 11:44 UTC
when checking the validation log the "col" value is 0 or 1 no matter where the error happens.

**Comment by alexandru-m-g** [comment] 2018-04-24 14:25
Another example: https://beta.proxy.hxlstandard.org/data/validate.json?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F19oLyom0jNYSZJKXgbPKEVYbdlv8zIAuGGRYJAYttOb0%2Fedit%23gid%3D0&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fmaster%2Fvalidation-schema-gin.json

**Comment by davidmegginson** [comment] 2018-04-25 01:55
Fixed in HXLStandard/libhxl-python#135 and deployed to beta.

Confirmation link (error should be in column 3 #targeted): 

https://beta.proxy.hxlstandard.org/data/validate.json?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1rOO0-xYa3kIOfI-6KR-mLgMTdgIEijNxM52Nfhs8uvg%2Fedit%23gid%3D0&schema_url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1rOO0-xYa3kIOfI-6KR-mLgMTdgIEijNxM52Nfhs8uvg%2Fedit%23gid%3D853725811&details=pp8GCCen

**Comment by davidmegginson** [comment] 2018-04-25 01:56
@alexandru-m-g or @danmihaila -- please confirm, and close if the problem is resolved.

**Closed** 2018-04-25 08:47 UTC
Labels: bug, high-priority, medium effort, tested, to close
