### ISSUE TITLE
Show the row offset in the error reports 

### ISSUE THREAD

**Issue by alexandru-m-g** [HXLStandard/hxl-proxy#202] opened 2018-04-24 08:07 UTC
The idea is for the user to be able to figure out the exact row in the original file where the error happened.
So he/she should know, when they see error in "row 19" what they should add to this to get the original row in their excel file.

**Comment by davidmegginson** [comment] 2018-04-24 21:49
This will mostly be handled in HXLStandard/libhxl-python#134, but keeping this issue open in case there are implications for the HXL Proxy after moving JSON generation to libhxl (see HXLStandard/libhxl-python#132)

**Comment by davidmegginson** [comment] 2018-04-25 02:49
Resolved in libhxl, and also needed to make a small change in the HXL Proxy.

There is now a new property in the JSON, _source\_row,_ that provides the row number in the original source (zero-based, so add 1 for spreadsheet users). the _row_ property still gives the logical HXL data row.

Confirmation link: https://beta.proxy.hxlstandard.org/data/validate.json?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1rOO0-xYa3kIOfI-6KR-mLgMTdgIEijNxM52Nfhs8uvg%2Fedit%23gid%3D0&schema_url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1rOO0-xYa3kIOfI-6KR-mLgMTdgIEijNxM52Nfhs8uvg%2Fedit%23gid%3D853725811&details=pp8GCCen

**Comment by davidmegginson** [comment] 2018-04-25 02:49
@alexandru-m-g -- please check and close if the issue is resolved.

**Comment by danmihaila** [comment] 2018-04-25 08:50
tested with @alexandru-m-g and it good!

**Closed by danmihaila** 2018-04-25 08:50 UTC
Labels: enhancement, high-priority, medium effort, to close
