### ISSUE TITLE
Unable to download Malawi 'National PMI/RBM.csv',  'Subnational Adult Mortality.csv',  'Subnational Maternal Mortality.csv',  'Subnational PMI/RBM.csv' data

### ISSUE THREAD

**Issue by SIMSON20** [HXLStandard/hxl-proxy#294] opened 2019-12-08 10:01 UTC
[HXL Proxy error.pdf](https://github.com/HXLStandard/hxl-proxy/files/3936077/HXL.Proxy.error.pdf)

**Comment by davidmegginson** [comment] 2019-12-09 17:04
Hi, @SIMSON20 , and thank you very much for the report. Would it be possible to send the full link that caused the error? (It's cut off at the bottom of the PDF). That would make it easier to reproduce and debug.

**Comment by davidmegginson** [comment] 2019-12-09 17:06
From a quick HDX search, I'm guessing it's this link:

https://proxy.hxlstandard.org/data/download/Subnational%20PMI/RBM.csv?url=https%3A%2F%2Fapi.dhsprogram.com%2Frest%2Fdhs%2Fdata%2FMW%3Ftagids%3D5%26breakdown%3Dsubnational%26perpage%3D10000%26f%3Dcsv&name=DHSHXL&header-row=1&tagger-match-all=on&tagger-01-header=dataid&tagger-01-tag=%23meta%2Bid&tagger-02-header=indicator&tagger-02-tag=%23indicator%2Bname&tagger-03-header=value&tagger-03-tag=%23indicator%2Bvalue%2Bnum&tagger-04-header=precision&tagger-04-tag=%23indicator%2Bprecision&tagger-06-header=countryname&tagger-06-tag=%23country%2Bname&tagger-07-header=surveyyear&tagger-07-tag=%23date%2Byear&tagger-08-header=surveyid&tagger-08-tag=%23survey%2Bid&tagger-09-header=indicatorid&tagger-09-tag=%23indicator%2Bcode&tagger-10-header=CharacteristicLabel&tagger-10-tag=%23meta%2Bcharacteristic&filter01=add&add-tag01=%23loc%2Bname&add-value01=%7B%7B%23meta%2Bcharacteristic%7D%7D&add-header01=Location&add-before01=on&filter02=add&add-tag02=%23country%2Bcode&add-value02=MWI&add-header02=ISO3&add-before02=on&filter03=replace&replace-pattern03=%5C.%5C.%28.%2A%29&replace-regex03=on&replace-value03=%5C1&replace-tags03=%23loc%2Bname&replace-where03=%23loc%2Bname~%5C.%5C..%2A

(Dataset: https://data.humdata.org/dataset/dhs-data-for-malawi)

**Comment by davidmegginson** [comment] 2019-12-09 17:08
The problem is the "/" in the download stub. The Proxy needs to be fixed to make sure the stub is URL-escaped.

**Comment by davidmegginson** [comment] 2019-12-09 17:48
Fixed in beta: https://beta.proxy.hxlstandard.org/data/7ab085

Still need to fix the download names in HDX, in the DHS data.

**Closed by davidmegginson** 2019-12-09 17:48 UTC
Labels: type:bug
