### ISSUE TITLE
Strip headers not applied if no action chosen afterwards

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#53] opened 2015-08-11 10:53 UTC
If you paste this URL: https://docs.google.com/spreadsheets/d/1Z4YWDKWnrSJPcyFEyHawRck0SrXg6R0hBriH7gBZuqA/pub?gid=975313202&single=true&output=csv
click update -> strip headers checkbox -> download as json then strip headers not applied.

To strip headers another event has to be carried out.

**Comment by davidmegginson** [comment] 2015-08-26 13:10
The problem also exists with CSV download.

If I create a filter and then delete it, the headers are removed properly.  Investigating.

**Comment by davidmegginson** [comment] 2015-08-26 13:14
The problem is that simply checking the "Strip headers" box doesn't save it; it's necessary to click the "Update" button as well.  The current layout is confusing, because it looks like the Update button applies only to the URL; will change it before closing this issue.

**Closed** 2015-08-26 13:20 UTC
Labels: bug
