### ISSUE TITLE
[bug] Updating the source of an existing recipe results in error

### ISSUE THREAD

**Issue by tinok** [HXLStandard/hxl-proxy#179] opened 2018-01-23 19:57 UTC
When trying to update the source file after generating a recipe, the tool shows a `'NoneType' object has no attribute 'encode'` error. 

To reproduce: 
1. Create new project with [this file](https://kc.kvar.kbtdev.org/pmusaraj/reports/aJu4ogVgKTBixqDZQJBBdt/export.xlsx)
1. Add HXL tags, save it
1. Then go back to the Source tab. 
1. Option 1: Don't change the source at all, just click the 'Next' tab
1. Option 2: Change the source tab to any other file 

Project where error occurred: https://beta.proxy.hxlstandard.org/data/UQy-uy/source

![image](https://user-images.githubusercontent.com/673511/35297663-b454dda0-004d-11e8-81cb-02c11527cc3a.png)

**Comment by davidmegginson** [comment] 2018-01-23 20:15
Thanks for the report. I'm looking now, and should have a time to deploy a fix before the 1.5 release at the end of this month (to beta before that).

**Comment by davidmegginson** [comment] 2018-01-24 20:22
Can't edit the linked saved recipe (don't have the password), so made a new one following the instructions here:

https://proxy.hxlstandard.org/data/F92pzq

**Comment by davidmegginson** [comment] 2018-01-24 20:23
Successfully reproduced the error following the steps in the description.

**Comment by davidmegginson** [comment] 2018-01-24 20:32
The problem was a missing hidden form field on the data source page. It should have had the recipe-id saved to include in the form submission. Fixed with 
fa6faf8

**Comment by davidmegginson** [comment] 2018-01-24 20:35
Deployed to https://beta.proxy.hxlstandard.org and tested OK.

@tinok - if you have a chance, could you repeat your steps on the beta Proxy (you'll have to save a new dataset, since it has a different short-URL database) and confirm that you're no longer having the problem? Closing for now, but will reopen if the fix doesn't work for you.

**Closed by davidmegginson** 2018-01-24 20:35 UTC
Labels: bug, quick fix

**Comment by tinok** [comment] 2018-02-01 15:03
Fix works, thanks!
